units:
  angle: -8
  P: 0.6U
points:
  zones:
    matrix:
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [100, -100]
      rotate: angle
      mirror: &mirror
        ref: matrix_inner_home
        shift: [0, -U]
        distance: 70
      columns:
        outer:
          key:
            column_net: P4
            mirror.column_net: P9
          rows:
            top:
              skip: true
        pinky:
          key:
            column_net: P5
            mirror.column_net: P8
          rows:
            top:
              skip: true
        ring:
          key:
            stagger: 0.25U
            column_net: P6
            mirror.column_net: P7
        middle:
          key:
            stagger: 0.25U
            column_net: P7
            mirror.column_net: P6
        index:
          key:
            stagger: -0.25U
            column_net: P8
            mirror.column_net: P5
        inner:
          key:
            stagger: -0.25U
            column_net: P9
            mirror.column_net: P4
      rows:
        bottom:
          padding: U
          row_net: P19
          mirror.row_net: P14
        home:
          padding: U
          row_net: P20
          mirror.row_net: P15
        top:
          padding: U
          row_net: P21
          mirror.row_net: P18
    thumb_middle:
      mirror: *mirror
      anchor:
        ref: matrix_inner_bottom
        shift: [0.75U, -1.4U]
        rotate: -angle
      key:
        name: thumb_middle
        row_net: P16
        column_net: P5
        mirror.column_net: P6
        rotate: angle
    thumb_reachy:
      mirror: *mirror
      anchor:
        ref: thumb_middle
        shift: [-1.25U, 0.15U]
        rotate: 2angle
      key:
        name: thumb_reachy
        row_net: P16
        column_net: P4
        mirror.column_net: P7
outlines:
  raw:
    - what: rectangle
      size: [U, U]
      where: true
  keycaps:
    - what: rectangle
      where: true
      size: [U-0.5, U-0.5]
  keys:
    - what: rectangle
      where: true
      size: [14, 14]
  board:
    - what: polygon
      operation: stack
      fillet: 3
      points:
        - ref: matrix_outer_home
          shift: [-P, P]
        - ref: matrix_middle_top
          shift: [-1.75P, P]
        - ref: matrix_middle_top
          shift: [1.75P, P]
        - ref: matrix_inner_top
          shift: [0, P]
        - ref: mirror_matrix_inner_top
          shift: [0, P]
        - ref: mirror_matrix_middle_top
          shift: [1.75P, P]
        - ref: mirror_matrix_middle_top
          shift: [-1.75P, P]
        - ref: mirror_matrix_outer_home
          shift: [-P, P]
        - ref: mirror_matrix_outer_bottom
          shift: [-P, -P]
        - ref: mirror_matrix_middle_bottom
          shift: [0, -2P]
        - ref: mirror_thumb_reachy
          shift: [-0.75P, -P]
        - ref: mirror_thumb_middle
          shift: [-0.5P, -1.2P]
        - ref: thumb_middle
          shift: [-0.5P, -1.2P]
        - ref: thumb_reachy
          shift: [-0.75P, -P]
        - ref: matrix_middle_bottom
          shift: [0, -2P]
        - ref: matrix_outer_bottom
          shift: [-P, -P]
  top-plate:
    - name: board
    - name: keys
      operation: subtract
  preview:
    - name: board
    - name: keycaps
      operation: subtract

pcbs:
  raveniung:
    template: kicad8
    outlines:
      main:
        outline: board
    footprints:
      mx-switches:
        what: ceoloide/switch_mx
        where: true
        params:
          solder: true
          hotswap: false
          include_keycap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diodes:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      mcu:
        what: ceoloide/mcu_nice_nano
        params:
          reverse_mount: true
        where:
          ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
          shift: [0, -5.15]
      power-switch:
        what: ceoloide/power_switch_smd_side
        where:
          ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
          shift: [-17, 9.4]
          rotate: 90
